package com.financetracker.ia.domain;

public enum TipoInsight {
    CARTAO_PREVISAO,
    COBRANCA_DUPLICADA,
    PROJECAO_PARCELAS,
    MELHOR_CARTAO,
    FADIGA_ASSINATURA,
    REAJUSTE_SILENCIOSO,
    ASSINATURA_ESQUECIDA,
    SUGESTAO_VENCIMENTO,
    ESTOURO_FATURA,
    AVISO_FECHAMENTO,

    // ── Novos insights (expansão comportamental) ──────────────────────
    MICRO_TRANSACOES,
    ORCAMENTO_SOBRA_META,
    DINHEIRO_DORMINDO,
    RADAR_FIM_SEMANA,
    QUEDA_RECEITA,
    REFORCO_POSITIVO,
    ACELERADOR_METAS,
    INFLACAO_PESSOAL
}
