-- Atualiza a CHECK constraint da tabela ia_insights para incluir os 8 novos tipos de insight
-- comportamental: MICRO_TRANSACOES, ORCAMENTO_SOBRA_META, DINHEIRO_DORMINDO,
-- RADAR_FIM_SEMANA, QUEDA_RECEITA, REFORCO_POSITIVO, ACELERADOR_METAS, INFLACAO_PESSOAL

ALTER TABLE ia_insights DROP CONSTRAINT IF EXISTS ia_insights_tipo_check;

ALTER TABLE ia_insights ADD CONSTRAINT ia_insights_tipo_check CHECK (tipo IN (
    'CARTAO_PREVISAO',
    'COBRANCA_DUPLICADA',
    'PROJECAO_PARCELAS',
    'MELHOR_CARTAO',
    'FADIGA_ASSINATURA',
    'REAJUSTE_SILENCIOSO',
    'ASSINATURA_ESQUECIDA',
    'SUGESTAO_VENCIMENTO',
    'ESTOURO_FATURA',
    'AVISO_FECHAMENTO',
    'MICRO_TRANSACOES',
    'ORCAMENTO_SOBRA_META',
    'DINHEIRO_DORMINDO',
    'RADAR_FIM_SEMANA',
    'QUEDA_RECEITA',
    'REFORCO_POSITIVO',
    'ACELERADOR_METAS',
    'INFLACAO_PESSOAL'
));
