-- Ativando Row Level Security (RLS) para todas as tabelas para mitigar a vulnerabilidade de acesso público via Supabase Data API

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE contas ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE faturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE metas_economia ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacoes_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE agendamentos_transacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE orcamentos_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;
