-- Ativando Row Level Security (RLS) para todas as tabelas listadas no alerta de segurança do Supabase.
-- Isso previne acesso não autorizado através da Supabase Data API (PostgREST).

ALTER TABLE cartoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE contas ENABLE ROW LEVEL SECURITY;
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE dashboard_layout ENABLE ROW LEVEL SECURITY;
ALTER TABLE desejos_compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE faturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE metas_economia ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_dicionario_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_correcoes_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE orcamentos_categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE agendamentos_transacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_classificacoes_assinatura ENABLE ROW LEVEL SECURITY;
